# Applied after project(), before the NCP targets exist.
if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    return()
endif()
include_guard(GLOBAL)

if(CMAKE_VERSION VERSION_LESS 3.19)
    message(FATAL_ERROR "The NCP runtime link hook requires CMake 3.19 or newer")
endif()

function(ncp_link_ppu_wrapper)
    if(NOT NCP_BUILD_MOE)
        return()
    endif()
    if(NOT TARGET ncp_moe)
        message(FATAL_ERROR "NCP_BUILD_MOE is ON but the ncp_moe target is missing")
    endif()
    get_filename_component(compiler_dir "${CMAKE_CUDA_COMPILER}" DIRECTORY)
    get_filename_component(sdk_root "${compiler_dir}/../.." ABSOLUTE)
    foreach(lib_dir IN ITEMS "${sdk_root}/targets/x86_64-linux/lib" "${sdk_root}/lib")
        if(EXISTS "${lib_dir}/libhggc_wrapper.so")
            set(ppu_include "")
            foreach(include_dir IN ITEMS "${sdk_root}/targets/x86_64-linux/include" "${sdk_root}/include")
                if(EXISTS "${include_dir}/hggc_runtime_api.h" AND EXISTS "${include_dir}/hggc.h" AND EXISTS "${include_dir}/hgrtc.h")
                    set(ppu_include "${include_dir}")
                    break()
                endif()
            endforeach()
            if(NOT ppu_include)
                message(FATAL_ERROR "PPU SDK at ${sdk_root} has no native host runtime headers")
            endif()
            # DeepGEMM host C++ needs native PPU headers, not only CUDA toolkit headers.
            target_include_directories(ncp_moe BEFORE PRIVATE "${ppu_include}")
            message(STATUS "ncp_moe PPU include: ${ppu_include}")
            # The CUDA compatibility entry hggcGetDeviceProperties_v2 is in the wrapper, not libhggcrt.
            set_property(TARGET ncp_moe APPEND PROPERTY LINK_LIBRARIES "${lib_dir}/libhggc_wrapper.so")
            message(STATUS "ncp_moe PPU runtime: ${lib_dir}/libhggc_wrapper.so")
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "PPU SDK at ${sdk_root} has no libhggc_wrapper.so")
endfunction()

cmake_language(DEFER CALL ncp_link_ppu_wrapper)
